### ISSUE TITLE
Concider the Node.js version for this repo

### ISSUE THREAD

**Issue by sukima** [TechLifeWeb/tw5tribalknowledge#1]
The Node.JS use of TiddlyWiki will save changes as `.tid` files and is much better for contributions via a Git repository.

Might I suggest that this repo use indevidual `.tid` files instead of a compiled single page TW file. I would be happy to do this is push a Pull Request if you like.

**Comment by TechLifeWeb** [comment]
Great suggestion. Thanks for offering to help. I'll do it first because I
need the project as a learning experience :) I'll reach out if I can't
fingure some thing out.
